import random

QUESTION_POOL = {
    "daily_life": [
        "¿Qué hiciste hoy por la mañana?",
        "¿Qué desayunaste hoy?",
        "¿A qué hora te levantaste hoy?",
        "¿Qué planes tienes para esta noche?",
        "¿Fuiste a algún sitio interesante esta semana?",
        "¿Qué comiste para comer hoy?",
        "¿Cómo fue tu día?",
        "¿Qué hiciste el fin de semana pasado?",
        "¿Tienes algo especial esta semana?",
        "¿A qué hora sueles acostarte normalmente?",
        "¿Qué vas a hacer después de esta conversación?",
        "¿Cuándo fue la última vez que cocinaste algo? ¿Qué hiciste?",
    ],
    "opinions": [
        "¿Cuál es tu película favorita y por qué?",
        "¿Qué tipo de música te gusta escuchar?",
        "¿Prefieres el café o el té por la mañana?",
        "¿Cuál es tu comida favorita?",
        "¿Qué harías si tuvieras un día libre mañana?",
        "¿Qué serie estás viendo últimamente?",
        "¿Prefieres el verano o el invierno?",
        "¿Cuál es tu libro favorito?",
        "¿Qué opinas de las redes sociales?",
        "Si pudieras vivir en cualquier ciudad del mundo, ¿cuál elegirías?",
        "¿Prefieres quedarte en casa o salir los fines de semana?",
        "¿Qué es lo que más te gusta hacer cuando tienes tiempo libre?",
    ],
    "spain_context": [
        "¿Has visitado España alguna vez?",
        "¿Qué sabes del barrio de Gràcia en Barcelona?",
        "Si fueras a Barcelona, ¿qué te gustaría visitar primero?",
        "¿Conoces algún plato típico catalán?",
        "Imagina que estás en un mercado en Madrid. ¿Qué comprarías?",
        "¿Qué sabes de la Sagrada Família?",
        "¿Conoces alguna palabra o expresión en catalán?",
        "¿Has probado alguna vez la paella o las tapas?",
        "¿Qué ciudades españolas te gustaría visitar?",
        "¿Sabes qué es la siesta y por qué es importante en España?",
        "Si estuvieras en Barcelona un domingo, ¿qué harías?",
    ],
    "soccer": [
        "¿Viste el último partido del Barça?",
        "¿Quién crees que es el mejor jugador del mundo ahora mismo?",
        "¿Qué opinas del estilo de juego del Barcelona?",
        "¿Tienes un jugador favorito? ¿Por qué te gusta?",
        "Si pudieras ir a un partido en el Camp Nou, ¿con quién irías?",
        "¿Qué equipo te parece el más difícil de enfrentar en La Liga?",
        "¿Crees que el Barça puede ganar la Champions este año?",
        "¿Cuál es el mejor gol que recuerdas haber visto?",
        "¿Prefieres ver el fútbol en casa o en un estadio?",
        "¿Quién crees que es mejor, Messi o Cristiano Ronaldo?",
        "¿Cómo crees que fue el último partido que viste?",
        "¿Qué posición te parece la más importante en el fútbol?",
    ],
    "social": [
        "¿Tienes hermanos o eres hijo único?",
        "¿Cómo es un día normal para ti?",
        "¿Qué haces cuando quieres relajarte?",
        "¿Con quién vives actualmente?",
        "¿Tienes alguna afición especial aparte del fútbol?",
        "¿Cómo conociste a tus mejores amigos?",
        "¿Qué haces los fines de semana normalmente?",
        "¿Tienes mascota?",
        "¿Estudias o trabajas?",
        "¿Cómo es tu ciudad o barrio?",
        "¿Qué es lo que más valoras en un amigo?",
        "¿Cuándo fue la última vez que viste a tu familia?",
    ],
    "situational": [
        "Imagina que entras en un bar en Sevilla. El camarero te pregunta qué quieres. ¿Qué dices?",
        "Conoces a alguien en una fiesta en Barcelona. ¿Cómo te presentas?",
        "Estás perdido en el centro de Madrid. ¿Cómo pides ayuda?",
        "Llegas tarde a quedar con un amigo español. ¿Qué le dices?",
        "Estás en un restaurante y quieres pedir la cuenta. ¿Cómo lo haces?",
        "Quieres comprar una camiseta del Barça en una tienda. ¿Qué preguntas?",
        "Tu amigo español te pregunta qué quieres hacer esta tarde. ¿Qué propones?",
        "Estás en la playa en Barcelona y alguien te pregunta la hora. ¿Qué dices?",
        "Quieres reservar una mesa en un restaurante por teléfono. ¿Qué dices?",
    ],
}


def get_opening_question() -> dict:
    category = random.choice(list(QUESTION_POOL.keys()))
    question = random.choice(QUESTION_POOL[category])
    return {"question": question, "category": category}
